---
title: "Cillo et al Rela Nivo - Figure 6"
output: html_document
---

## Load packages

```{r}
# Activate renv
renv::activate("./r_environment/renv_figs")

## Load packages
library(tidyverse)
library(ggplot2)
library(patchwork)
library(ggrastr)
library(survival)
library(survminer)
library(survMisc)
library(ggplotify)
library(lme4)
library(multcomp)
select <- dplyr::select

```


## Load data and set options 

```{r}

## Load data
fig6_data <- readRDS("./Data/cillo_et_al_figure_6_data.rds")

## Setup colors for fill
gene_set_colors <- RColorBrewer::brewer.pal("Set2",n=4)
names(gene_set_colors) <- c("Immune Score","Nivo signature",
                            "Rela signature","Rela+Nivo signature")

## NB: This data is only available upon request from https://zenodo.org/records/5747250
## To re-run this script, users will need to request permission from the owners of this data
fig6_data_part2 <- readRDS("./Data/huuhtanen_et_al_lag3_pd1_scrnaseq_summary.rds")

```

## Create figure

```{r}

## Schema for Huuhtanen et al LAG3+PD1 study 
p1 <- plot_spacer()

## Plot of T cell umap 
p2 <- fig6_data_part2 %>%
  ggplot(.,aes(x=UMAP_1,y=UMAP_2,colour=cell_types)) +
  rasterize(geom_point(colour="black",size=0.8)) +
  rasterize(geom_point(size=0.6,alpha=0.3)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.border = element_blank(),
        legend.position="right") +
  guides(colour = guide_legend(title="T cell types",override.aes = list(size=3,alpha=1))) +
  ggtitle("Huuhtanen et al\nPBMC - T cells") +
  xlab("UMAP_1") +
  ylab("UMAP_2")

## Linear mixed effector model for response - week 4
gene_set_significance <- fig6_data_part2 %>%
  filter(timepoint=="1") %>%
  filter(cell_types=="CD8+ T cells") %>%
  mutate(best_response_class=ifelse(best_response %in% c("CR","PR"),"CR/PR","PD")) %>%
  mutate(best_response_class=as.factor(best_response_class)) %>% 
  mutate(best_response_class=factor(best_response_class,levels=c("PD","CR/PR"))) %>%
  select(patient,combo,best_response_class) %>%
  afex::mixed(combo~best_response_class+(1|patient)-1,data=.)

response_model_data <- fig6_data_part2 %>%
  filter(timepoint=="1") %>%
  filter(cell_types=="CD8+ T cells") %>%
  mutate(best_response_class=ifelse(best_response %in% c("CR","PR"),"CR/PR","PD")) %>%
  mutate(best_response_class=as.factor(best_response_class)) %>% 
  mutate(best_response_class=factor(best_response_class,levels=c("PD","CR/PR"))) %>%
  select(patient,combo,best_response_class) 

glht(lmer(combo~best_response_class+(1|patient)-1,data=response_model_data),
             linfct=mcp(best_response_class = 'Tukey')) %>%
        summary(.,test=adjusted('fdr'))

mod_est <- lmer(combo~best_response_class+(1|patient)-1,data=response_model_data)
mod_conf <- confint(lmer(combo~best_response_class+(1|patient)-1,data=response_model_data))
        
conf_ints_comb <- left_join(fixef(mod_est) %>%
                              enframe(.,name="group",value="fixed_eff"),
                            mod_conf %>%
                              as_tibble(.,rownames="group"),by="group")

set1 <- data.frame(conf_ints_comb) %>%
  mutate(`Best response`=gsub("best_response_class","",group)) %>%
  mutate(`Best response`=as.factor(`Best response`)) %>% 
  mutate(`Best response`=factor(`Best response`,levels=c("PD","CR/PR"))) %>% 
  select(-group)

colnames(set1)[2:3] <- c("lower_bound","upper_bound")

p3 <- ggplot(set1,aes(x=`Best response`,y=fixed_eff,ymin=lower_bound,ymax=upper_bound,fill=`Best response`)) +
  geom_crossbar() +
  theme_bw() +
  theme(legend.position="none") +
  ylab("Rela+Nivo treatment\nenrichment score") +
  ggtitle("Huuhtanen et al PBMC\nCD8+ T cells - Week 4")

## IO cohorts schema 
p4 <- plot_spacer()

## Survival analysis 
p5 <- as.ggplot(ggsurvplot(survfit(Surv(OS.time,OS)~ImmuneScore,data=fig6_data[[2]]),pval=T,conf.int=T,surv.median.line="hv",risk.table=T)$plot)
p6 <- as.ggplot(ggsurvplot(survfit(Surv(OS.time,OS)~rela,data=fig6_data[[2]]),pval=T,conf.int=T,surv.median.line="hv",risk.table=T)$plot)
p7 <- as.ggplot(ggsurvplot(survfit(Surv(OS.time,OS)~nivo,data=fig6_data[[2]]),pval=T,conf.int=T,surv.median.line="hv",risk.table=T)$plot)
p8 <- as.ggplot(ggsurvplot(survfit(Surv(OS.time,OS)~combo,data=fig6_data[[2]]),pval=T,conf.int=T,surv.median.line="hv",risk.table=T)$plot)

## Survival states
coxph(Surv(OS.time,OS)~ImmuneScore,data=fig6_data[[2]])
coxph(Surv(OS.time,OS)~rela,data=fig6_data[[2]])
coxph(Surv(OS.time,OS)~nivo,data=fig6_data[[2]])
coxph(Surv(OS.time,OS)~combo,data=fig6_data[[2]])

## Flow schema
p9 <- plot_spacer() 

flow_group_colors <- gene_set_colors
names(flow_group_colors) <- c("NA","Nivo","Rela","Combo")

p10 <- fig6_data[[3]] %>% 
  group_by(patient_id) %>%
  mutate(pid_count=n()) %>%
  ungroup() %>%
  filter(pid_count>1) %>%
  filter(!time=="HD") %>% 
  mutate(tx=as.factor(tx)) %>%
  mutate(tx=factor(tx,levels=c("rela","nivo","combo"))) %>%
  mutate(tx=recode(tx,rela="Rela",nivo="Nivo",combo="Combo")) %>% 
  mutate(time=recode(time,Wk4="Week 4")) %>% 
  ggplot(.,aes(x=time,y=cd38pos_tim3pos,fill=tx)) +
  geom_violin() +
  geom_point() +
  geom_line(aes(group=patient_id)) +
  stat_summary(fun="mean",
               geom="crossbar",
               width=0.5,
               colour="black") +
  facet_wrap(~tx,ncol=3) +
  theme_bw() +
  scale_fill_manual(values=flow_group_colors) +
  theme(legend.position="none") + 
  xlab("Timepoint") +
  ylab("CD38+ TIM3+\n(Frequency of CD8+ T cells)")

fig6_data[[3]] %>% 
  group_by(patient_id) %>%
  mutate(pid_count=n()) %>%
  ungroup() %>%
  filter(pid_count>1) %>%
  filter(!time=="HD") %>% 
  mutate(tx=as.factor(tx)) %>%
  mutate(tx=factor(tx,levels=c("rela","nivo","combo"))) %>%
  mutate(tx=recode(tx,rela="Rela",nivo="Nivo",combo="Combo")) %>% 
  mutate(time=recode(time,Wk4="Week 4")) %>%
  split(.$tx) %>%
  map(~t.test(cd38pos_tim3pos~time,data=.,paired=T))

```
