---
title: "Cillo et al Rela Nivo - Figure 5"
output: html_document
---

## Load packages
```{r}
# Activate renv
renv::activate("./r_environment/renv_figs5")

## Load packages
library(tidyverse)
library(ggplot2)
library(patchwork)
library(pheatmap)
library(lazyeval)
library(miloR)
library(ggrastr)
library(ggplotify)
library(igraph)
library(ggraph)
library(tidygraph)

```


## Load data and set options 

```{r}

fig5_data <- readRDS("./Data/cillo_et_al_figure_5_data.rds")

## Define colors for visualization
tx_group_colors <- RColorBrewer::brewer.pal("Set2",n=4)
names(tx_group_colors) <- c("Baseline","Nivo","Rela","Rela+Nivo")

colours_use <- RColorBrewer::brewer.pal(3,"Set2")[c(2,1)]

```

## Function to annotate heatmap

```{r}

## Function to label individual rows in pheatmap 
add.flag <- function(pheatmap,
                     kept.labels,
                     repel.degree) {
  
  # repel.degree = number within [0, 1], which controls how much
  #                space to allocate for repelling labels.
  ## repel.degree = 0: spread out labels over existing range of kept labels
  ## repel.degree = 1: spread out labels over the full y-axis
  
  heatmap <- pheatmap$gtable
  
  new.label <- heatmap$grobs[[which(heatmap$layout$name == "row_names")]]
  
  # keep only labels in kept.labels, replace the rest with ""
  new.label$label <- ifelse(new.label$label %in% kept.labels,
                            new.label$label, "")
  
  # calculate evenly spaced out y-axis positions
  repelled.y <- function(d, d.select, k = repel.degree){
    # d = vector of distances for labels
    # d.select = vector of T/F for which labels are significant
    
    # recursive function to get current label positions
    # (note the unit is "npc" for all components of each distance)
    strip.npc <- function(dd){
      if(!"unit.arithmetic" %in% class(dd)) {
        return(as.numeric(dd))
      }
      
      d1 <- strip.npc(dd$arg1)
      d2 <- strip.npc(dd$arg2)
      fn <- dd$fname
      return(lazyeval::lazy_eval(paste(d1, fn, d2)))
    }
    
    full.range <- sapply(seq_along(d), function(i) strip.npc(d[i]))
    selected.range <- sapply(seq_along(d[d.select]), function(i) strip.npc(d[d.select][i]))
    
    return(unit(seq(from = max(selected.range) + k*(max(full.range) - max(selected.range)),
                    to = min(selected.range) - k*(min(selected.range) - min(full.range)),
                    length.out = sum(d.select)),
                "npc"))
  }
  new.y.positions <- repelled.y(new.label$y,
                                d.select = new.label$label != "")
  new.flag <- grid::segmentsGrob(x0 = new.label$x,
                                 x1 = new.label$x + unit(0.15, "npc"),
                                 y0 = new.label$y[new.label$label != ""],
                                 y1 = new.y.positions)
  
  # shift position for selected labels
  new.label$x <- new.label$x + unit(0.2, "npc")
  new.label$y[new.label$label != ""] <- new.y.positions
  
  # add flag to heatmap
  heatmap <- gtable::gtable_add_grob(x = heatmap,
                                     grobs = new.flag,
                                     t = 4,
                                     l = 4
  )
  
  # replace label positions in heatmap
  heatmap$grobs[[which(heatmap$layout$name == "row_names")]] <- new.label
  
  # plot result
  grid::grid.newpage()
  grid::grid.draw(heatmap)
  
  # return a copy of the heatmap invisibly
  invisible(heatmap)
}

```

## Create figure

```{r}

## Milo neighborhoods plots 
p1 <- rasterize( fig5_data[[1]][[1]] +
  ggtitle("Neighborhoods") +
  theme(legend.position="none")
)

p2 <- rasterize( fig5_data[[1]][[2]] +
  scale_fill_gradient2(low="purple",mid="black",high="yellow",limits=c(-5,5)) +
  ggtitle("Rela") +
  theme(legend.position="none")
)

p3 <- rasterize( fig5_data[[1]][[3]] +
  scale_fill_gradient2(low="yellow",mid="black",high="purple",limits=c(-5,5)) +
  ggtitle("Nivo") +
  theme(legend.position="none")
)

p4 <- rasterize( fig5_data[[1]][[4]] + 
  scale_fill_gradient2(low="yellow",mid="black",high="purple",limits=c(-5,5)) +
  ggtitle("Rela + Nivo") +
  theme(legend.position="none")
)

## Legend 
p4x <- fig5_data[[1]][[4]] + 
  scale_fill_gradient2(low="purple",mid="black",high="yellow",limits=c(-5,5))

legend <- cowplot::get_legend(p4x)
p4_l <- ggplotify::as.ggplot(legend)

## Heatmap of DEGs
out <- pheatmap::pheatmap(fig5_data[[3]],scale="row",color=colorRampPalette(colors=c("purple","black","yellow"))(1024))

out2 <- add.flag(out,kept.labels=c(
  "CD44","JUN","JUNB","GNLY","KLF4","CD81","GZMH","HLA.DQA2","HLA.DRB5","JUND",
  "BATF","CCL3","CCL4","CCL5","CD38","CXCL13","CXCR3","CXCR6","EOMES",
  "FASLG","GZMA","GZMB","GZMK","HAVCR2","IFNG","LAG3","PDCD1","PRDM1","PRF1",
  "STAT1","TOX",
  "IFI44L","IFIT1","MX1","MX2",
  "IFITM1","IFITM3","IFI27","IFI35","ISG15","ISG20"
),
repel.degree=0.1)

p5 <- as.ggplot(out2)

## Highlight ability of TF to explain DEGs
p6 <- fig5_data[[5]][["rela"]] %>%
  top_n(10,TF_genes_explained) %>%
  ggplot(.,aes(x=reorder(TF,-TF_genes_explained),y=TF_genes_explained)) + 
  geom_col(fill=tx_group_colors[3]) +
  xlab("TF module") +
  ylab("Number of genes in TF module") +
  ggtitle("Rela") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=TRUE))

p7 <- fig5_data[[5]][["nivo"]] %>%
  top_n(10,TF_genes_explained) %>%
  ggplot(.,aes(x=reorder(TF,-TF_genes_explained),y=TF_genes_explained)) + 
  geom_col(fill=tx_group_colors[2]) +
  xlab("TF module") +
  ylab("Number of genes in TF module") +
  ggtitle("Nivo") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=TRUE))

p8 <- fig5_data[[5]][["combo"]] %>%
  filter(!TF=="SEMA4A") %>%
  top_n(10,TF_genes_explained) %>%
  ggplot(.,aes(x=reorder(TF,-TF_genes_explained),y=TF_genes_explained)) +
  geom_col(fill=tx_group_colors[4]) +
  xlab("TF module") +
  ylab("Number of genes in TF module") +
  ggtitle("Rela + Nivo") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=TRUE))

## Create graph of TFs that drive rela+nivo DEGs
combo_top_tfs <-  fig5_data[[6]][["combo"]] %>%
  filter(!TF=="SEMA4A") %>%
  select(TF) %>%
  distinct() %>%
  pull()

g1 <- fig5_data[[4]] %>%
  filter(TF %in% combo_top_tfs) %>% 
  group_by(TF) %>%
  top_n(100,mean_importance) %>%
  mutate(in_set=target %in% c(fig5_data[[2]][["combo"]],combo_top_tfs)) %>% 
  filter(in_set==TRUE) %>%
  filter(!TF=="SEMA4A") %>%
  graph_from_data_frame(.,directed=T)

p9 <- as_tbl_graph(g1) %>%
  mutate(color="Inferred Target") %>%
  mutate(color=ifelse(name %in% combo_top_tfs,"TF",color)) %>% 
  mutate(color=ifelse(name=="SEMA4A","Inferred Target",color)) %>%
  ggraph(.,layout="graphopt") +
  geom_edge_link() +
  geom_node_label(aes(label=name,fill=color),size=2.25) +
  xlab("") +
  ylab("") +
  theme_classic() +
  theme(axis.line=element_blank(),
        axis.text=element_blank(),
        axis.ticks = element_blank()) +
  guides(
    fill = guide_legend(
      title = "",
      override.aes = aes(label = "")
    )
  ) +
  ggtitle("Rela + Nivo")

```
